public class TriggersManager {

	public static Boolean StopAllZuoraProductTriggers = false;
	public static Boolean StopAllSubscriptionTriggers = false;
	public static Boolean StopAllZuoraPaymentTriggers = false;
	public static Boolean StopAllZuoraInvoiceTriggers = false;
	public static Boolean StopAllZuoraSubscriptionProductChargeTriggers = false;
	public static Boolean StopAllZuoraPaymentMethodTriggers = false;
	public static Boolean stopAllZuoraSubscriptionRatePlanTriggers = false;
    
    public static Boolean StopContentDocumentLinkTrigger = false;
}