public with sharing class ZuoraSubscriptionRatePlanTriggerHandler {
    /*public static void synchSubscriptionRatePlan(Boolean nuevo, List<Zuora__SubscriptionRatePlan__c> newList) {
        List<Id> listIds = new List<Id>();
        for(Zuora__SubscriptionRatePlan__c srp : newList) {
            listIds.add(srp.Id);
        }
        callDSP(nuevo, listIds);
    }

    public static void callDSP(Boolean nuevo, List<Id> listIds) {
        FAN_Callout.enviarSRP(nuevo, listIds);
    }*/
}